export const FETCHED_PHYCISIANS = "FETCHED_PHYCISIANS";
export const FETCHED_APPOINTMENTS = "FETCHED_APPOINTMENTS";
export const SELECT_PHYCISIAN = "SELECT_PHYCISIAN";
export const SELECTED_PHYCISIAN = "SELECTED_PHYCISIAN";
